### ISSUE TITLE
Usage in flexdashboard and runtime shiny

### ISSUE THREAD

**Issue by dirkdegel** [INWTlab/shiny-matrix#9] opened 2020-03-24 05:13 UTC
Hi all, I'm totally new to this package and it is something I was looking for for a while.

I found this article:
https://www.r-bloggers.com/shinymatrix-matrix-input-for-shiny-apps/
and used the code to build the app.R file and it worked perfectly fine.

Usually I use flexdashboards with the shiny runtime. I tried to use the same code but was not able to get it running. Please find a minimal example below. 

Any help is much appreciated.

Thanks Dirk

```
---
title: "shinyMatrix Package"
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---

```{r global, include = FALSE}

library(shinyMatrix) # https://github.com/INWTlab/shiny-matrix

```

Sidebar {.sidebar}
=====================================================================================================================

Matrix

```{r}

m <- matrix(runif(12), 6, 2, dimnames = list(NULL, c("x", "y")))

matrixInput(
  inputId = "sample", 
  value = m,
  #inputClass = matrix-input,
  rows = list(extend = TRUE), 
  cols = list(names = TRUE),
  class = "numeric",
  paste = TRUE,
  copy = TRUE
)

```

Matrix
=====================================================================================================================

Column
---------------------------------------------------------------------------------------------------------------------

### Display Plot

```{r}

renderPlot({
  plot(input$sample, col = "red", main = "Scatterplot")
})

```

```

**Comment by Ljupch0** [comment] 2020-04-15 22:44
Flexdashboard + runtime shiny has been very buggy in my experience. Try replicating in a regular shiny app?

**Comment by aneudecker** [comment] 2020-04-21 13:59
Hi @dirkdegel 

thanks for reporting this. I am not sure how flexdashboard includes the javascript and css files. Could you post the page source from the flexdashboard page to see if the shiny-matrix dependencies are included at all?

**Comment by amitghosh-inwt** [comment] 2020-04-21 14:18
I also tried to reproduce this. The `<div>` section created by `shinyMatrix` is actually included in the output of your flexdashboard (you can see it, when using the "Inspect element"). However it's not properly displayed in the HTML. It seems indeed, that shinyMatrix and flexdashboard are not compatible. It will require modifications in one of the two packages to make it work.

**Comment by aneudecker** [comment] 2020-05-07 07:25
I am closing this because it seems like a flexdashboard issue.

**Closed by aneudecker** 2020-05-07 07:25 UTC
Labels: question
